[build]
    command = "make build"

[build.environment]
    # Change this path with the path to your repository
    GO_IMPORT_PATH = "github.com/cbosss/functions-playground"

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = '''
        max-age=63072000;
        includeSubDomains;
        preload'''

[[redirects]]
    from = "/internal/*"
    to = "/.netlify/internal/:splat"
