[build]
    functions = "functions"

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = '''
        max-age=63072000;
        includeSubDomains;
        preload'''

[[redirects]]
    from = "/internal/*"
    to = "/.netlify/internal/:splat"
    status = 200
